services:
  app:
    image: rap-map-cloud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80" 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"