name: CI_workflow_test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  deploy:
    
    runs-on: [ubuntu-latest]
    steps:
    #  code checkout 
      - name: checkout code
        uses: actions/checkout@v2

    #  reading package json for version
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        with:
          path: "./landing-node"
        id: package-version

    # keeping track of docker image on the hub 

      # login in to dockerhub
      - name: Docker login
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # pushing image
      - name: build and push 
        id: docker_build 
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./landing-node/rap.Dockerfile
          push: true
          tags: landscapedatacommons/rap_node:${{ steps.package-version.outputs.version }}

    # deploy on remote server
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP}}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker service update rap_rap-landing \
            --image=docker.io/landscapedatacommons/rap_node:${{ steps.package-version.outputs.version }}