name: Deploy to AWS Fargate

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Read package.json
        uses: krstphrrr/package-json-version-reader@v1.0.0
        with: 
          path: "./rangeland-analysis-platform/"
        id: package-version


      - name: Build and Push Docker image to ECR
        id: build-image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/rapmap-cloud-ecr:${{ steps.package-version.outputs.version }}
            ${{ steps.login-ecr.outputs.registry }}/rapmap-cloud-ecr:latest

      # Simplify task definition preparation for Angular app (no secrets needed)
      - name: Prepare Task Definition
        run: |
          sed -e "s|__VERSION__|${{ steps.package-version.outputs.version }}|" \
              ecs-task-def.json.tpl > ecs-task-def.json

      - name: Update ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.1
        with:
          task-definition: ecs-task-def.json
          service: rapmap-service
          cluster: rapmap-cluster
          wait-for-service-stability: true